### PR TITLE
put enhancements

### PR DESCRIPTION
**Pull request by fb55**
Added methods to upload data not available as files (as strings or streams).

### CODE REVIEW

**Comment by evnm** [comment]
Can you give an example usage of the `getPutStream` API?

**Comment by fb55** [comment]
After you called it, it will return a write stream (with the usual methods as .write() and .end()). The idea was to write files from  read streams directly (eg. downloads) to Dropbox, without the need of a buffer. I'm not quite sure if it's fully supported by Dropbox, I just tested it with a 50kb text file.

**Comment by evnm** [comment]
I definitely understand the use case. This is definitely desired functionality. However, I can't seem to get it to work. The first chunk passed directly to `put` gets written, but the rest of the stream is ignored.

Here's the example I'm working with, after modifying your changes a bit (mostly style and naming):

```
var filename = "somefile.txt";
var req = dropbox.putFileStream(filename, "")  // Put filename at path within Dropbox root.
  , read_stream = require('fs').createReadStream(filename, { bufferSize: 64*1024 });

read_stream.on('data', function (chunk) { req.write(chunk); });
read_stream.on('end', function () { req.end(); });
```

This code runs to completion, but the resulting uploaded file is empty.

**Comment by fb55** [comment]
About your code: If there is no first chunk, you shouldn't receive a stream. I'm using <a href="https://github.com/ciaranj/node-oauth/blob/master/lib/oauth.js#L344">this</a> behavior of the oauth lib to get a stream in return. For my testing, I created the stream after the first chunk was available.

Anyway, it is possible that Dropbox just permits the "stay-alive"-header for open connections. This would result in the effect we are seeing right now.

**Comment by evnm** [comment]
Can you give an example that works for you? Even if I supply a first chunk, only that chunk is written.

I modified your changes a bit, as per the following diff. In particular, I changed getPutStream to putFileStream and modified the signature so it doesn't take an explicit first chunk.

https://gist.github.com/550487b5b48c61e019ec

**Comment by nils-werner** [comment]
The [Dropbox Docs](https://www.dropbox.com/developers/docs#files) say

> Please note: the Dropbox API doesn't currently support uploading using chunked encoding. We recommend multipart encoding.

Maybe that's the reason.

**Comment by evnm** [comment]
Exactly. Between Dropbox's lack of support for chunked encoding and the fact that their current API explicitly targets mobile and not web development, I've been hesitant to move forward with streaming uploads.

**Pull request closed without merging**
