### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by seven1m**
fix npm install instructions

### CODE REVIEW

**Comment by blockloop** [comment]
Must do. I debugged for a few minutes before I found out I had the wrong package.

**Comment by seven1m** [comment]
@evnm would just take you two seconds to merge this and save a lot of noobs trouble.

**Comment by evnm** [comment]
Whoops. Wasn't getting notifications for this repo for some reason, so just now noticed it. Thanks!

**Comment by seven1m** [comment]
Great thanks!

**Pull request merged**
